spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/bikongyouran/microservicespringclouddemo
          username:
          password:
          label: master
#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native
  application:
    name: config-server
server:
  port: 8769
