spring:
  cloud:
    config:
      server:
        server:
          git:
            uri:
            searchPaths: respo
            username:
            password:
        label: master
#        native:
#          search-locations: classpath:/shared
#  profiles:
#    active: native
  application:
    name: config-server
server:
  port: 8769
